=== FaaSr/FaaSr-package/schema/FaaSr.schema.json
{
  "$comment":"A JSON schema to validate a FaaSr payload, using R library: https://cran.r-project.org/web/packages/jsonvalidate/vignettes/jsonvalidate.html",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://flare-forecast.org/FaaSr.schema.json",
  "title": "FaaSr invocation payload",
  "description": "Schema for an invocation of FaaSr",
  "type": "object",
  "properties": {
    "FunctionInvoke": {
      "description": "The name of the R function to be invoked by this action",
      "type": "string",
      "minLength": 1
    },
    "InvocationID": {
      "description": "The unique ID used throughout all action invocations for this workflow",
      "type": "string"
    },
    "LoggingDataStore": {
      "description": "The name of the logging server to use - must match an S3 server defined under DataStores",
      "type": "string"
    },
    "DefaultDataStore": {
      "description": "The name of the default server to use - must match an S3 server defined under DataStores",
      "type": "string",
      "minLength": 1
    },
    "FaaSrLog": {
      "description": "The name of the Log file's folder",
      "type": "string"
    },
    "FunctionList": {
      "description": "A list of one or more functions that describes the workflow",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "minProperties": 1,
      "patternProperties": {
        "":{
          "type":"object",
          "properties":{
            "FaaSServer":{"type":"string","minLength": 1},
            "FunctionName":{"type":"string","minLength": 1},
            "Arguments":{"type":"object"},
            "InvokeNext":{
            "type": ["string", "array"],
            "items": {
              "type": "string",
              "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*(?:\\[(TRUE|FALSE)\\])?(?:\\([0-9]+\\))?$"
            }
          },
            "Rank":{"type":"string"}
          },
          "required":["FaaSServer", "FunctionName"],
          "additionalProperties": false
        }
      }
    },
    "ComputeServers": {
      "description": "A list of one or more FaaS compute servers used in the workflow",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties": {
        "":{
          "type":"object",
          "properties":{
            "FaaSType":{"enum":["OpenWhisk", "GitHubActions", "Lambda"]},
            "Region":{"type":"string","minLength": 1},
            "Endpoint":{"type":"string","minLength": 1},
            "Namespace":{"type":"string","minLength": 1},
            "API.key":{"type":"string","minLength": 1},
            "AccessKey":{"type":"string","minLength": 1},
            "SecretKey":{"type":"string","minLength": 1},
            "UserName":{"type":"string","minLenght": 1},
            "ActionRepoName":{"type":"string","minLenght": 1},            
            "Token":{"type":"string","minLength": 1},
            "Branch":{"type":"string"},
            "SSL":{"type":"string","minLength": 1}
          },
          "additionalProperties":false,
          "allOf":[
            {
              "if": {
                "properties": {"FaaSType":{"const": "OpenWhisk"}},
                "required":["FaaSType"]
              },
              "then": {
                "required":["Endpoint", "Namespace", "API.key"]
              }
            },
            {
              "if": {
                "properties": {"FaaSType":{"const": "Lambda"}},
                "required":["FaaSType"]
              },
              "then": {
                "required":["Region", "AccessKey", "SecretKey"]
              }
            },
            {
              "if": {
                "properties": {"FaaSType":{"const": "GitHubActions"}},
                "required":["FaaSType"]
              },
              "then": {
                "required":["UserName", "ActionRepoName", "Token"]
              }
            }
          ]
        }
      }
    },
    "DataStores": {
      "description": "A list of one or more S3 data servers used in the workflow",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties": {
        "":{
            "type":"object",
            "properties":{
              "Endpoint":{"type":"string"},
              "AccessKey":{"type":"string","minLength": 1},
              "SecretKey":{"type":"string","minLength": 1},
              "Bucket":{"type":"string","minLength": 1},
              "Region":{"type":"string"},
              "Writable":{"type":"string","minLength": 1},
              "Anonymous":{"type":"string","minLength": 1}
            },
            "required":["AccessKey", "SecretKey", "Bucket"],
            "additionalProperties": false
        }
      }
    },
   "ActionContainers": {
      "description": "A mapping of action names to containers(Docker Hub)",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties": {
        "":{"type":"string","minLength": 1}
      }
    },
   "FunctionGitRepo": {
      "description": "User R code from github Repository",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties":{
        "":{"type":["string", "array"]}
        }
    },
   "FunctionCRANPackage": {
      "description": "User R code from CRAN package",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties":{
        "":{"type":["string", "array"]}
        }
    },
   "FunctionGitHubPackage": {
      "description": "User R package from github Repository",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties":{
        "":{"type":["string", "array"]}
        }
    }
  },
  "required": [ "FunctionInvoke", "DefaultDataStore", "FunctionList", "ComputeServers", "DataStores"]
}

=== FaaSr/FaaSr-package/tests/testthat/test.json
{   "FunctionInvoke": "first_action",
    "InvocationID": "uuid_format_id",
    "FaaSrLog": "logfolder_name/default:FaaSrLog",
    "DefaultDataStore": "Servername for logging/should be one of DataStores Server name",
    "LoggingDataStore": "Logging server name",
    "FunctionList": {
        "F1": {
            "FaaSServer": "target_faas_server/should be one of ComputeServers Server name",
            "FunctionName": "F1_function_name",
            "Arguments": {
                "input1": "input1.csv",
                "input2": "input2.csv"
            },
            "InvokeNext": [
                "F2",
                "F3"
            ]
        },
        "F2": {
            "FaaSServer": "My_Github_Account",
            "FunctionName": "F2_function_name",
            "Arguments": {
                "input": "input3.csv"
            }
        },
        "F3": {
            "FaaSServer": "My_AWS_Account",
            "FunctionName": "F3_function_name",
            "Arguments": {
                "input": "input123.csv"
            }
        }
    },
    "ActionContainers": {
        "f3_action": "user_docker_id/user_custom_image"
    },
    "FunctionCRANPackage": {
        "F2": [
            "cran_package",
            "cran_package_1"
        ],
        "F3": [
            "dpkg",
            "dplyr"
        ]
    },
    "FunctionGitHubPackage": {
        "F1": [
            "github_package",
            "github_package_1"
        ],
        "F2": [
            "FLARE-forecast/FLAREr",
            "FaaSr/FaaSr-package"
        ]
    },
    "FunctionGitRepo": {
        "F1": [
            "git_repository",
            "git_repository1"
        ],
        "F3": [
            "user_id/user_repo",
            "user_id_1/user_repo_1"
        ]
    },
    "ComputeServers": {
        "My_Github_Account": {
            "FaaSType": "GitHubActions",
            "UserName": "user_name",
            "ActionRepoName": "repo_name",
            "Branch": "branch1",
            "Token": "git_token" 
        },
        "My_AWS_Account": {
            "FaaSType": "Lambda",
            "AccessKey": "lambda_access_key",
            "SecretKey": "lambda_secret_key",
            "Region": "test"
        },
        "My_IBM_Account": {
            "FaaSType": "OpenWhisk",
            "Endpoint": "http://00.00.00.00",
            "Namespace": "my_namespace",
            "API.key": "ow_api_key"
        }
    },
    "DataStores": {
        "My_S3_Account": {
            "Endpoint": "",
            "Bucket": "my_bucket",
            "Region": "us-east-1",
            "Writable": "TRUE",
            "AccessKey": "s3_access_key",
            "SecretKey": "s3_secret_key"
        },
        "My_Minio_Account": {
            "Endpoint": "https://play.min.io",
            "Bucket": "my_bucket1",
            "Region": "",
            "Writable": "TRUE",
            "AccessKey": "minio_access_key",
            "SecretKey": "minio_secret_key"
        }
    }
}
